# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: TerraformTaskV2@2
  inputs:
    provider: 'aws'
    command: 'init'
    backendServiceAWS: 'aws terraform connection'
    backendAWSBucketName: 'dev-applications-backend-state-mehtachirag186-tf'
    backendAWSKey: '/dev/07-backend-state/users/backend-state/backend.tfstate'

   
- task: TerraformTaskV2@2
  inputs:
    provider: 'aws'
    command: 'apply'
    environmentServiceNameAWS: 'aws terraform connection'

